#ALTER TABLE ciudades ADD latitud SMALLINT;
#ALTER TABLE ciudades ADD longitud SMALLINT;

SET SQL_SAFE_UPDATES = 0;
UPDATE `dp1`.`ciudades` SET `nombre`='Montevideo' WHERE `cod_ciudad`='SUAA';


UPDATE ciudades c SET c.latitud = 4.711 , c.longitud = -74.072 WHERE c.nombre = "Bogota";
UPDATE ciudades c SET c.latitud = -0.181 , c.longitud = -78.468 WHERE c.nombre = "Quito";
UPDATE ciudades c SET c.latitud = 10.481 , c.longitud = -66.904 WHERE c.nombre = "Caracas";
UPDATE ciudades c SET c.latitud = -14.235 , c.longitud = -51.925 WHERE c.nombre = "Brasilia";
UPDATE ciudades c SET c.latitud = -12.046 , c.longitud = -77.042 WHERE c.nombre = "Lima";
UPDATE ciudades c SET c.latitud = -16.489 , c.longitud = -68.119 WHERE c.nombre = "La Paz";
UPDATE ciudades c SET c.latitud = -33.448 , c.longitud = -70.669 WHERE c.nombre = "Santiago de Chile";
UPDATE ciudades c SET c.latitud = -34.603 , c.longitud = -58.381 WHERE c.nombre = "Buenos Aires";
UPDATE ciudades c SET c.latitud = -25.263 , c.longitud = -57.575 WHERE c.nombre = "Asunción";
UPDATE ciudades c SET c.latitud = -34.901 , c.longitud = -56.164 WHERE c.nombre = "Montevideo";
UPDATE ciudades c SET c.latitud = 41.327 , c.longitud = 19.818 WHERE c.nombre = "Tirana";
UPDATE ciudades c SET c.latitud = 52.52 , c.longitud = 13.404 WHERE c.nombre = "Berlin";
UPDATE ciudades c SET c.latitud = 48.208 , c.longitud = 16.373 WHERE c.nombre = "Viena";
UPDATE ciudades c SET c.latitud = 50.85 , c.longitud = 4.351 WHERE c.nombre = "Bruselas";
UPDATE ciudades c SET c.latitud = 53.904 , c.longitud = 27.561 WHERE c.nombre = "Minsk";
UPDATE ciudades c SET c.latitud = 42.697 , c.longitud = 23.321 WHERE c.nombre = "Sofia";
UPDATE ciudades c SET c.latitud = 50.075 , c.longitud = 14.437 WHERE c.nombre = "Praga";
UPDATE ciudades c SET c.latitud = 45.815 , c.longitud = 15.981 WHERE c.nombre = "Zagreb";
UPDATE ciudades c SET c.latitud = 55.676 , c.longitud = 12.568 WHERE c.nombre = "Copenhague";
UPDATE ciudades c SET c.latitud = 48.148 , c.longitud = 17.107 WHERE c.nombre = "Bratislava";
UPDATE ciudades c SET c.latitud = 46.056 , c.longitud = 14.505 WHERE c.nombre = "Liubliana";
UPDATE ciudades c SET c.latitud = 40.416 , c.longitud = -3.703 WHERE c.nombre = "Madrid";
UPDATE ciudades c SET c.latitud = 59.436 , c.longitud = 24.753 WHERE c.nombre = "Tallin";
UPDATE ciudades c SET c.latitud = 60.169 , c.longitud = 24.938 WHERE c.nombre = "Helsinki";
UPDATE ciudades c SET c.latitud = 48.856 , c.longitud = 2.352 WHERE c.nombre = "Paris";
UPDATE ciudades c SET c.latitud = 37.983 , c.longitud = 23.727 WHERE c.nombre = "Atenas";
UPDATE ciudades c SET c.latitud = 52.37 , c.longitud = 4.895 WHERE c.nombre = "Amsterdam";
UPDATE ciudades c SET c.latitud = 47.497 , c.longitud = 19.04 WHERE c.nombre = "Budapest";
UPDATE ciudades c SET c.latitud = 40.099 , c.longitud = -83.114 WHERE c.nombre = "Dublin";
UPDATE ciudades c SET c.latitud = 59.436 , c.longitud = 24.753 WHERE c.nombre = "Tallin";
UPDATE ciudades c SET c.latitud = 64.126 , c.longitud = -21.817 WHERE c.nombre = "Reykjavik";
UPDATE ciudades c SET c.latitud = 41.902 , c.longitud = 12.496 WHERE c.nombre = "Roma";
UPDATE ciudades c SET c.latitud = 56.949 , c.longitud = 24.105 WHERE c.nombre = "Riga";
UPDATE ciudades c SET c.latitud = 49.815 , c.longitud = 6.129 WHERE c.nombre = "Luxemburgo";
UPDATE ciudades c SET c.latitud = 35.898 , c.longitud = 14.514 WHERE c.nombre = "LaValletta";
UPDATE ciudades c SET c.latitud = 59.913 , c.longitud = 10.752 WHERE c.nombre = "Oslo";
UPDATE ciudades c SET c.latitud = 52.229 , c.longitud = 21.012 WHERE c.nombre = "Varsovia";
UPDATE ciudades c SET c.latitud = 38.722 , c.longitud = -9.139 WHERE c.nombre = "Lisboa";
UPDATE ciudades c SET c.latitud = 51.507 , c.longitud = -0.127 WHERE c.nombre = "Londres";
UPDATE ciudades c SET c.latitud = 59.329 , c.longitud = 18.068 WHERE c.nombre = "Estocolmo";
UPDATE ciudades c SET c.latitud = 46.947 , c.longitud = 7.447 WHERE c.nombre = "Berna";

#ALTER TABLE ciudades ADD huso SMALLINT;

UPDATE ciudades c SET c.huso = -5 WHERE c.cod_ciudad = "SKBO";
UPDATE ciudades c SET c.huso = -5 WHERE c.cod_ciudad = "SEQM";
UPDATE ciudades c SET c.huso = -4 WHERE c.cod_ciudad = "SVMI";
UPDATE ciudades c SET c.huso = -3 WHERE c.cod_ciudad = "SBBR";
UPDATE ciudades c SET c.huso = -5 WHERE c.cod_ciudad = "SPIM";
UPDATE ciudades c SET c.huso = -4 WHERE c.cod_ciudad = "SLLP";
UPDATE ciudades c SET c.huso = -3 WHERE c.cod_ciudad = "SCEL";
UPDATE ciudades c SET c.huso = -3 WHERE c.cod_ciudad = "SABE";
UPDATE ciudades c SET c.huso = -4 WHERE c.cod_ciudad = "SGAS";
UPDATE ciudades c SET c.huso = -3 WHERE c.cod_ciudad = "SUAA";
UPDATE ciudades c SET c.huso = 2 WHERE c.cod_ciudad = "LATI";
UPDATE ciudades c SET c.huso = 2 WHERE c.cod_ciudad = "EDDI";
UPDATE ciudades c SET c.huso = 2 WHERE c.cod_ciudad = "LOWW";
UPDATE ciudades c SET c.huso = 2 WHERE c.cod_ciudad = "EBCI";
UPDATE ciudades c SET c.huso = 3 WHERE c.cod_ciudad = "UMMS";
UPDATE ciudades c SET c.huso = 3 WHERE c.cod_ciudad = "LBSF";
UPDATE ciudades c SET c.huso = 2 WHERE c.cod_ciudad = "LKPR";
UPDATE ciudades c SET c.huso = 2 WHERE c.cod_ciudad = "LDZA";
UPDATE ciudades c SET c.huso = 2 WHERE c.cod_ciudad = "EKCH";
UPDATE ciudades c SET c.huso = 2 WHERE c.cod_ciudad = "LZIB";
UPDATE ciudades c SET c.huso = 2 WHERE c.cod_ciudad = "LJLJ";
UPDATE ciudades c SET c.huso = 2 WHERE c.cod_ciudad = "LEMD";
UPDATE ciudades c SET c.huso = 3 WHERE c.cod_ciudad = "EETN";
UPDATE ciudades c SET c.huso = 3 WHERE c.cod_ciudad = "EFHK";
UPDATE ciudades c SET c.huso = 2 WHERE c.cod_ciudad = "LFPG";
UPDATE ciudades c SET c.huso = 3 WHERE c.cod_ciudad = "LGAV";
UPDATE ciudades c SET c.huso = 2 WHERE c.cod_ciudad = "EHAM";
UPDATE ciudades c SET c.huso = 2 WHERE c.cod_ciudad = "LHBP";
UPDATE ciudades c SET c.huso = 1 WHERE c.cod_ciudad = "EIDW";
UPDATE ciudades c SET c.huso = 0 WHERE c.cod_ciudad = "BIKF";
UPDATE ciudades c SET c.huso = 1 WHERE c.cod_ciudad = "LIRA";
UPDATE ciudades c SET c.huso = 2 WHERE c.cod_ciudad = "EVRA";
UPDATE ciudades c SET c.huso = 1 WHERE c.cod_ciudad = "ELLX";
UPDATE ciudades c SET c.huso = 1 WHERE c.cod_ciudad = "LMML";
UPDATE ciudades c SET c.huso = 1 WHERE c.cod_ciudad = "ENGM";
UPDATE ciudades c SET c.huso = 1 WHERE c.cod_ciudad = "EPMO";
UPDATE ciudades c SET c.huso = 0 WHERE c.cod_ciudad = "LPPT";
UPDATE ciudades c SET c.huso = 1 WHERE c.cod_ciudad = "EGLL";
UPDATE ciudades c SET c.huso = 1 WHERE c.cod_ciudad = "ESKN";
UPDATE ciudades c SET c.huso = 2 WHERE c.cod_ciudad = "LSZB";